# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    # Python35:
    #   python.version: '3.8'
    # Python36:
    #   python.version: '3.9'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -e .
    pip install numpy --upgrade
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest --cov=ConceptFingerprint --cov-report=xml tests -W ignore::DeprecationWarning
  displayName: 'pytest'

- script: |
    bash <(curl -s https://codecov.io/bash) -t $(codecovToken)
  displayName: 'Uploading to codecov.io'
